"""
Scribe - AI-powered documentation generator
"""
"""Confluence publishing module for Scribe."""

import requests
from typing import Dict, Optional

from .config import Config


class ConfluencePublisher:
    """Publishes documentation to Confluence"""
    
    def __init__(self, config: Config):
        self.config = config
        self.auth = (config.confluence_username, config.confluence_api_token)
        self.base_url = config.confluence_url
        
    def publish(self, title: str, content: str, space_key: Optional[str] = None, parent_id: Optional[str] = None) -> Dict:
        """Publish or update a page in Confluence"""
        
        space_key = space_key or self.config.confluence_space_key
        
        # Check if page exists
        existing_page = self._find_page(title, space_key)
        
        if existing_page:
            # If parent_id is specified and different from current parent, we need to handle this
            if parent_id:
                current_parent_id = None
                if 'ancestors' in existing_page and existing_page['ancestors']:
                    current_parent_id = existing_page['ancestors'][-1]['id']
                
                if str(parent_id) != str(current_parent_id):
                    print(f"[WARNING] Page already exists but under a different parent.")
                    print(f"Current parent ID: {current_parent_id}")
                    print(f"Requested parent ID: {parent_id}")
                    print("Confluence doesn't support moving pages via API. The page will be updated in its current location.")
            
            # Update existing page
            return self._update_page(existing_page['id'], title, content, existing_page['version']['number'])
        else:
            # Create new page
            return self._create_page(title, content, space_key, parent_id)
    
    def publish_multi_page(self, title: str, sections: Dict[str, str], space_key: Optional[str] = None, 
                          parent_id: Optional[str] = None) -> Dict:
        """Publish documentation as multiple pages with a parent-child structure"""
        
        space_key = space_key or self.config.confluence_space_key
        
        # Create or update main page
        main_content = self._create_main_page_content(title, sections.keys())
        main_page = self.publish(title, main_content, space_key, parent_id)
        
        # Create or update child pages
        for section_title, section_content in sections.items():
            child_title = f"{title} - {section_title}"
            try:
                self.publish(child_title, section_content, space_key, main_page['id'])
                print(f"  ✓ Published section: {section_title}")
            except Exception as e:
                print(f"  ✗ Failed to publish section {section_title}: {e}")
        
        return main_page
    
    def _create_main_page_content(self, title: str, sections: list) -> str:
        """Create the main page content with links to sections"""
        
        content = f"""<h1>{title}</h1>

<ac:structured-macro ac:name="children">
    <ac:parameter ac:name="all">true</ac:parameter>
    <ac:parameter ac:name="sort">title</ac:parameter>
</ac:structured-macro>

<p><em>Generated by Codex - AI-powered documentation generator</em></p>"""
        
        return content
    
    def _find_page(self, title: str, space_key: str) -> Optional[Dict]:
        """Find a page by title in a space"""
        
        url = f"{self.base_url}/rest/api/content"
        params = {
            'title': title,
            'spaceKey': space_key,
            'expand': 'version,ancestors'
        }
        
        response = requests.get(url, params=params, auth=self.auth)
        
        if response.status_code == 200:
            results = response.json()['results']
            return results[0] if results else None
        
        return None
    
    def _create_page(self, title: str, content: str, space_key: str, parent_id: Optional[str] = None) -> Dict:
        """Create a new Confluence page"""
        
        url = f"{self.base_url}/rest/api/content"
        
        data = {
            'type': 'page',
            'title': title,
            'space': {'key': space_key},
            'body': {
                'storage': {
                    'value': content,
                    'representation': 'storage'
                }
            }
        }
        
        if parent_id:
            data['ancestors'] = [{'id': parent_id}]
        
        response = requests.post(
            url,
            json=data,
            auth=self.auth,
            headers={'Content-Type': 'application/json'}
        )
        
        if response.status_code not in [200, 201]:
            raise Exception(f"Failed to create page: {response.status_code} - {response.text}")
        
        return response.json()
    
    def _update_page(self, page_id: str, title: str, content: str, version: int) -> Dict:
        """Update an existing Confluence page"""
        
        url = f"{self.base_url}/rest/api/content/{page_id}"
        
        data = {
            'id': page_id,
            'type': 'page',
            'title': title,
            'body': {
                'storage': {
                    'value': content,
                    'representation': 'storage'
                }
            },
            'version': {
                'number': version + 1
            }
        }
        
        response = requests.put(
            url,
            json=data,
            auth=self.auth,
            headers={'Content-Type': 'application/json'}
        )
        
        if response.status_code != 200:
            raise Exception(f"Failed to update page: {response.status_code} - {response.text}")
        
        return response.json()
